---
machines:
  gal_web:
    hostname: "gal-web"
    ipv4: "192.168.60.10"
    bridge: "192.168.60.1"
    playbook: "provisioning/ansible/web_server.yml"
    port_map:
    - { guest: 80, host: 8080 }
    - { guest: 443, host: 4430 }
    folder_map:
    - { guest: "/opt/www", host: "../" }
    services:
    - "nginx"
    - "hhvm"

  gal_db:
    hostname: "gal-db"
    ipv4: "192.168.60.20"
    bridge: "192.168.60.1"
    playbook: "provisioning/ansible/db_server.yml"
    services:
    - "mysql"

  gal_cache:
    hostname: "gal-cache"
    ipv4: "192.168.60.30"
    bridge: "192.168.60.1"
    playbook: "provisioning/ansible/cache_server.yml"
    services:
    - "memcached"
