parameters:
    gallery_core.controller.class: Gallery\Bundle\CoreBundle\Controller\Controller
    gallery_core.controller.homepage.class: Gallery\Bundle\CoreBundle\Controller\HomepageController
    gallery_core.controller.about.class: Gallery\Bundle\CoreBundle\Controller\AboutController

services:
    gallery_core.controller:
        class: "%gallery_core.controller.class%"
        abstract: true
        calls:
            - [setTemplating, ["@templating"]]

    gallery_core.controller.homepage:
        class: "%gallery_core.controller.homepage.class%"
        parent: gallery_core.controller

    gallery_core.controller.about:
        class: "%gallery_core.controller.about.class%"
        parent: gallery_core.controller
