parameters:
    gallery_core.controller.homepage.class: Gallery\Bundle\CoreBundle\Controller\HomepageController

services:
    gallery_core.controller.homepage:
        class: %gallery_core.controller.homepage.class%
