# -*- mode: ruby -*-
# vi: set ft=ruby :

# NOTE: This Vagrantfile requires plugin vagrant-triggers:
#
# => $ vagrant plugin install vagrant-triggers

require "./helpers.rb"

VAGRANTFILE_API_VERSION = "2"
CONFIG_DIST  = "config/machines.yml"
CONFIG_LOCAL = "config/machines.local.yml"

config = ConfigHelper::getConfig(CONFIG_DIST, CONFIG_LOCAL)
machines = config["machines"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  machines.each do |name, machine|
    config.vm.define name do |node|
      # Machine image
      node.vm.hostname = machine["hostname"]
      node.vm.box = "ubuntu/trusty64"

      # VirtualBox Setup
      node.vm.provider "virtualbox" do |v|
        v.name = machine["hostname"]

        v.memory = 1024
        v.cpus = 4
      end

      # Network
      node.vm.network "private_network", ip: machine["ipv4"]

      # Forwarded ports
      if machine.include? "port_map"
        machine["port_map"].each do |forward|
          node.vm.network "forwarded_port", guest: forward["guest"], host: forward["host"]
        end
      end

      # Synced folders
      if machine.include? "folder_map"
        machine["folder_map"].each do |folder|
          node.vm.synced_folder folder["host"], folder["guest"], type: "nfs"
        end
      end

      # Provisioning
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = machine["playbook"]
        # ansible.verbose = "vvvv"
      end
    end
  end
end
