---
- name: Update Apt Cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install Prerequisites
  apt: name={{ item }} state=present
  with_items:
  - supervisor

- name: Install Supervisor Config
  template: src=../templates/supervisord.conf.j2 dest=/etc/supervisor/conf.d/supervisord.conf owner=root group=root
